version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio-dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    mem_limit: 2g
    memswap_limit: 2g

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: portfolio-prod
    environment:
      - NODE_ENV=production
    ports:
      - "3005:3000"
    env_file:
      - .env
    mem_limit: 2g
    memswap_limit: 2g

volumes:
  node_modules:
  .next: